name: BetterTrees
version: 1.0
description: Generate customized trees and forests, with saplings, brushes, and commands.
author: Kyle Nanakdewa
website: http://Akenland.com/plugins

main: com.kylenanakdewa.bettertrees.BetterTreesPlugin
depend: [WorldEdit]

commands:
  bettertrees:
    description: View plugin information, and reload the plugin.
    permission: bettertrees.admin
    usage: /bettertrees <version/reload>

  tree:
    description: Generate a tree or forest.
    permission: bettertrees.generate
    usage: /tree <type> [forest]

  treebrush:
    description: Get a tree brush, to generate many trees or forests.
    permission: bettertrees.brush
    usage: /treebrush <type> [forest]